---
title: "DV Lab Fat Q1"
author: "Bacham Venkat 20BCE1551"
date: "2023-04-11"
output: html_document
---

```{r}
data = mtcars
data$gear
count(data$gear)
plot(x = )
```

```{r}
### Question - Use the ‘count’ function to count the gear type and draw a bar graph that shows the number of gear type.
data = mtcars

barplot(table(mtcars$gear), main = "Frequency of Carburetors", col = c("maroon", "red", "orange", "yellow", "green", "grey"))
```


```{r}
### Question - Draw a pie chart showing the proportion of cars from that have different carb values. ‘Printing’ the dataset, and creating a table isolating the ‘carb’ variable.

mtcarscarb = table(mtcars$carb)
mtcarscarb
#Create percent label values
percentlabels<- round(100*mtcarscarb/sum(mtcarscarb), 1)
#Create labels for each pie in the chart
pielabels<- paste(percentlabels, "%", sep="")
#R code to create the Pie Chart
pie(mtcarscarb,col = rainbow(length(mtcarscarb)), labels = pielabels , main = 'Pie Chart of Proportion of Cars with Different Number of Carburetors', cex = 0.8)
 #Legend for the pie chart
legend("topright", c("Carb-1","Carb-2","Carb-3","Carb-4","Carb-6","Carb-8"), cex=0.6, fill=  rainbow(length(mtcarscarb)))
```










